name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@2023.1
        with:
          repository: openstack/glance
          ref: 1fd12c29b339f30fe823e2b5beba14b5f241e52a

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@2023.1
        with:
          repository: openstack/glance_store
          ref: 97b6f4c030189a80df0b525420a3760ae3a81941

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@2023.1
        with:
          image-name: glance
          build-contexts: |
            glance=openstack/glance
            glance_store=openstack/glance_store
          push: ${{ github.event_name != 'pull_request' }}
