name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@2024.2
        with:
          repository: openstack/glance
          ref: 097f38158189efc5c7d52fd56467455a58442c73

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@2024.2
        with:
          repository: openstack/glance_store
          ref: 6182b2b2fe640df4c763ae8fc6c04571374479a1

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@2024.2
        with:
          image-name: glance
          build-contexts: |
            glance=openstack/glance
            glance_store=openstack/glance_store
          push: ${{ github.event_name != 'pull_request' }}
